# Generated by Django 4.2 on 2023-05-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product_pimage_alter_product_cat_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdes',
            field=models.CharField(default=0, max_length=50, verbose_name='Product Description'),
            preserve_default=False,
        ),
    ]
